apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: darkwing
type: Opaque
stringData:
  KAFKA_USERNAME: testuser
  KAFKA_PASSWORD: testpass
  KAFKA_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="testuser" password="testpass";'
