apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: darkwing

resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-ingress.yaml
  - worker-deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
